### ISSUE TITLE
Filter lost after update

### ISSUE THREAD

**Issue by JmiXIII** [killkli/vue3_jspreadsheet#3]
Expected : When setting filter it should stay the same after updating data
(tested onlive jspreadsheet -> https://bossanova.uk/jspreadsheet/v4/examples/column-filters)

Actual :
When using docs vue3_jspreadsheet filter is lost once update is made (enter key)

For massiv updates this is damageable.

**Comment by killkli** [comment]
Thank you!!! you helped with finding problems~~
this is fixed with last commit~

Issue fixed with 9d42204dde469d69bd2f7fa7b21d27f09d21aa16

**Comment by killkli** [comment]
also update npm package, update the version to 0.3.1

**Comment by JmiXIII** [comment]
thanks for short correction. I'm just amater and using python + Vue for internal professionnal needs. Jspreadsheet is really good. I also like tabulatore but it lacks Vue3 support.
I have send an email to Jpsreadsheet-ce to explain it could be good to include your component in official doc

**Comment by JmiXIII** [comment]
Hi updated with npm install vue3jspreadsheet@0.3.1 => seems still not working

**Comment by killkli** [comment]
> Hi updated with npm install vue3jspreadsheet@0.3.1 => seems still not working

My bad@@, I forgot to rebuild npm bundle before publish the vewsion.
Bundle rebuilt now and bump the version to 0.3.2, it should be working now.
